import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, severityClass } from "@/lib/api";
import RiskMap from "@/components/RiskMap";
import { Warning, ShieldCheck, PersonSimpleWalk, WarningCircle } from "@phosphor-icons/react";

const LANGS={en:"English",as:"Assamese",kha:"Khasi",lus:"Mizo",ne:"Nepali",brx:"Bodo"};
export default function Public(){
 const [alerts,setAlerts]=useState([]),[zones,setZones]=useState([]),[lang,setLang]=useState("en");
 useEffect(()=>{Promise.all([api.get("/public/alerts"),api.get("/public/zones")]).then(([a,z])=>{setAlerts(a.data.slice(0,6));setZones(z.data)}).catch(()=>{});},[]);
 const criticalZones=zones.filter(z=>["CRITICAL","HIGH"].includes(z.latest?.severity));
 return <div className="min-h-screen" data-testid="public-page">
  <header className="tactical-border border-l-0 border-r-0 border-t-0 px-4 md:px-8 py-4 flex items-center gap-3"><div className="w-8 h-8 flex items-center justify-center bg-[var(--sev-critical)] text-white font-heading font-bold text-sm">NS</div><div><div className="font-heading font-bold tracking-tighter text-lg">NER-SLIDE · Public</div><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)]">Landslide risk & community reporting</div></div><div className="ml-auto flex items-center gap-2"><select value={lang} onChange={e=>setLang(e.target.value)} data-testid="public-lang" className="tactical-border bg-transparent px-2 py-1 text-xs font-mono uppercase tracking-[0.15em]">{Object.entries(LANGS).map(([c,l])=><option key={c} value={c}>{l}</option>)}</select><Link to="/field" className="chip sev-medium"><PersonSimpleWalk size={11}/> Field officer</Link><Link to="/login" className="chip sev-low"><ShieldCheck size={11}/> Ops sign-in</Link></div></header>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 p-4 md:p-8"><div className="lg:col-span-2 tactical-card overflow-hidden" style={{height:520}}><RiskMap publicMode layers={{zones:true,roads:true,villages:true,sensors:false,reports:false}}/></div><div className="space-y-4"><div className="tactical-card p-4" data-testid="public-alerts"><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)] mb-2 flex items-center gap-1"><Warning size={12}/> Active alerts</div><div className="space-y-2">{alerts.map(a=><div key={a.id} className="border border-[var(--border)] p-2"><span className={`chip ${severityClass(a.severity)}`}>{a.severity}</span><p className="text-xs mt-1">{a.translations?.[lang]||a.translations?.en||a.reason}</p></div>)}{!alerts.length&&<div className="font-mono text-xs text-[var(--text-2)]">No active alerts.</div>}</div></div><div className="tactical-card p-4"><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)] mb-2 flex items-center gap-1"><WarningCircle size={12}/> High-risk zones</div><div className="space-y-1">{criticalZones.slice(0,8).map(z=><div key={z.zone_id} className="flex items-center justify-between text-xs"><span>{z.name}</span><span className={`chip ${severityClass(z.latest?.severity)}`}>{z.latest?.severity}</span></div>)}{!criticalZones.length&&<div className="font-mono text-xs text-[var(--text-2)]">No zones at high or critical risk right now.</div>}</div></div><div className="tactical-card p-4"><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)] mb-2">Emergency instructions</div><ul className="text-xs leading-relaxed list-disc pl-4 space-y-1"><li>Move to higher, firm ground if you notice new cracks, seepage, or slope tilt.</li><li>Do not shelter under overhanging slopes or freshly-cut hill faces during rain.</li><li>Sign in before submitting a report so evidence is securely associated with your account.</li><li>Follow instructions from your district emergency operations centre.</li></ul></div></div></div>
 </div>;
}
